export const MAP_STYLE: google.maps.MapTypeStyle[] = [
  { elementType: 'geometry', stylers: [{ color: '#faf3e0' }] },
  { elementType: 'labels.text.fill', stylers: [{ color: '#baa898' }] },
  { elementType: 'labels.text.stroke', stylers: [{ color: '#faf3e0' }, { weight: 2 }] },
  { elementType: 'labels.icon', stylers: [{ visibility: 'off' }] },
  { featureType: 'administrative.country', elementType: 'labels', stylers: [{ visibility: 'off' }] },
  { featureType: 'administrative.province', elementType: 'labels', stylers: [{ visibility: 'off' }] },
  { featureType: 'administrative.locality', elementType: 'labels', stylers: [{ visibility: 'off' }] },
  { featureType: 'administrative.neighborhood', elementType: 'labels', stylers: [{ visibility: 'on' }] },
  { featureType: 'administrative.neighborhood', elementType: 'labels.text.fill', stylers: [{ color: '#b8a494' }] },
  { featureType: 'administrative.neighborhood', elementType: 'labels.text.stroke', stylers: [{ color: '#faf3e0' }, { weight: 3 }] },
  { featureType: 'administrative', elementType: 'geometry', stylers: [{ visibility: 'off' }] },
  { featureType: 'poi', elementType: 'labels', stylers: [{ visibility: 'off' }] },
  { featureType: 'poi', elementType: 'geometry', stylers: [{ color: '#f0e8da' }] },
  { featureType: 'poi.park', elementType: 'geometry.fill', stylers: [{ color: '#c6e8b4' }] },
  { featureType: 'landscape.man_made', elementType: 'geometry.fill', stylers: [{ color: '#fceee0' }] },
  { featureType: 'landscape.man_made', elementType: 'geometry.stroke', stylers: [{ color: '#e4daca' }, { weight: 0.5 }] },
  { featureType: 'landscape.natural', elementType: 'geometry.fill', stylers: [{ color: '#e4ecd8' }] },
  { featureType: 'road', elementType: 'labels', stylers: [{ visibility: 'off' }] },
  { featureType: 'road', elementType: 'geometry.fill', stylers: [{ color: '#f5e6d0' }] },
  { featureType: 'road', elementType: 'geometry.stroke', stylers: [{ visibility: 'off' }] },
  { featureType: 'road.local', elementType: 'geometry', stylers: [{ weight: 1.5 }] },
  { featureType: 'road.arterial', elementType: 'geometry', stylers: [{ weight: 2 }] },
  { featureType: 'road.arterial', elementType: 'labels', stylers: [{ visibility: 'on' }] },
  { featureType: 'road.arterial', elementType: 'labels.text.fill', stylers: [{ color: '#baa898' }] },
  { featureType: 'road.arterial', elementType: 'labels.text.stroke', stylers: [{ color: '#faf3e0' }, { weight: 3 }] },
  { featureType: 'road.highway', elementType: 'geometry', stylers: [{ weight: 2.5 }] },
  { featureType: 'road.highway', elementType: 'geometry.fill', stylers: [{ color: '#f5e6d0' }] },
  { featureType: 'water', elementType: 'geometry.fill', stylers: [{ color: '#b8d4f0' }] },
  { featureType: 'water', elementType: 'labels', stylers: [{ visibility: 'off' }] },
  { featureType: 'transit', stylers: [{ visibility: 'off' }] },
];
